export const ADD_EVENT = 'ADD_EVENT';
export const LOAD_EVENTS = ['LOAD_EVENTS', 'LOAD_EVENTS_SUCCESS', 'LOAD_EVENTS_FAIL'];
export const CREATE_EVENT = ['CREATE_EVENT', 'CREATE_EVENT_SUCCESS', 'CREATE_EVENT_FAIL'];
